jenkins-job.sh: relax the grep for MACHINE in bitbake.log (v1.8.42)
* there is different indentation in the log since this commit:
  http://git.openembedded.org/openembedded-core/commit/?id=e556b85a452a4ebf34a0c9581608f135bbad2e2c
  and the script was complaining that it doesn't match:
  ERROR: log log.world.qemuarm.20171111_045714.log//bitbake.log, isn't for MACHINE qemuarm

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>